"""Guardrails determinísticos (entrada, execução, saída)."""

from credito_agentes.guardrails.rules import (
    DESCONTO_MAXIMO,
    DISCLAIMER_REGULATORIO,
    PRAZO_MAXIMO_CONCESSAO,
    PRAZO_MAXIMO_RENEG,
    TAXA_MENSAL_MINIMA,
    TAXA_MENSAL_MINIMA_CONCESSAO,
    GuardrailOutcome,
    RateLimiter,
    authorized_numbers_from_options,
    authorized_numbers_from_proposal,
    check_input,
    check_output_toxicity,
    decision_coherence,
    enforce_hard_limits_concessao,
    enforce_hard_limits_reneg,
    ensure_disclaimer,
    numeric_non_hallucination,
    require_authentication,
    should_escalate,
    validate_tool_schema,
)

__all__ = [
    "DESCONTO_MAXIMO",
    "DISCLAIMER_REGULATORIO",
    "PRAZO_MAXIMO_CONCESSAO",
    "PRAZO_MAXIMO_RENEG",
    "TAXA_MENSAL_MINIMA",
    "TAXA_MENSAL_MINIMA_CONCESSAO",
    "GuardrailOutcome",
    "RateLimiter",
    "authorized_numbers_from_options",
    "authorized_numbers_from_proposal",
    "check_input",
    "check_output_toxicity",
    "decision_coherence",
    "enforce_hard_limits_concessao",
    "enforce_hard_limits_reneg",
    "ensure_disclaimer",
    "numeric_non_hallucination",
    "require_authentication",
    "should_escalate",
    "validate_tool_schema",
]
